### ISSUE TITLE
Calling 'Get-TwitterFollowers' results in exception

### ISSUE THREAD

**Issue by pauby** [PowerShellModules/Twitter#1]
I have setup $OAuth hashtable with the correct keys (I verified they work by using the PSTwitterAPI module):

```
> $OAuth = @{ ApiKey = 'blah'; ApiSecret = 'blah'; AccessToken = 'blah; AccessTokenSecret = 'blah' }
```

When I call `Get-TwitterFollowers -Screenname 'pauby' -Verbose' I get this error:

```
> Get-TwitterFollowers -ScreenName 'pauby' -Verbose
SetValueInvocationException: C:\Users\Paul\git\pauby\others\powershellmodules_twitter\Twitter\classes\OAuthParameters.Class.psm1:202
Line |
 202 |          $this.UriBuilder = $this.BaseUri
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "UriBuilder": "Cannot convert value "" to type "System.UriBuilder". Error: "Invalid
     | URI: The hostname could not be parsed.""

InvalidOperation: C:\Users\Paul\git\pauby\others\powershellmodules_twitter\Twitter\public\Get-TwitterFollowers.ps1:70
Line |
  70 |          $OAuthParameters.BaseUri = 'https://api.twitter.com/1.1/follo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'BaseUri' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: C:\Users\Paul\git\pauby\others\powershellmodules_twitter\Twitter\public\Get-TwitterFollowers.ps1:73
Line |
  73 |      $OAuthParameters.SetQuery($Query)
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Invoke-TwitterCursorRequest: C:\Users\Paul\git\pauby\others\powershellmodules_twitter\Twitter\public\Get-TwitterFollowers.ps1:79
Line |
  79 |  … owers = Invoke-TwitterCursorRequest -OAuthParameters $OAuthParameters
     |                                                         ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'OAuthParameters' because it is null
```

I've only had a cursory look over this at the moment so what I'm about to say may be nonsense 😄 

This [line](https://github.com/PowerShellModules/Twitter/blob/master/Twitter/public/Get-TwitterFollowers.ps1#L44) sets the `$BaseUri` to `$null`?

**Comment by thedavecarroll** [comment]
Apologies for not replying sooner.

This issue is occurring for all functions that are based on the `Invoke-TwitterCursorRequest` private function. I will correct this in a forthcoming update.

Also, this module will be released to the PowerShell Gallery quite soon, as a prerelease.

**Comment by thedavecarroll** [comment]
This has been fixed.

Please note that the `followers/list` endpoint has a rate limit of 15.

Now that the function is using `New-TwitterQuery` to generate the query from the `$PSBoundParameters`, when I set the default `ResultsPerPage`, it is not updating the `$PSBoundParameters` hashtable.

I'll create a new issue to track the work on parameters.
